"""
conftest.py — Playwright Test Configuration and Fixtures
=========================================================
Shared fixtures for all Playwright smoke and functional tests.

Playwright is used for Python-native browser automation, running smoke
and functional tests against the live portfolio site after deployment.

Fixtures:
  base_url    — The base URL for the site under test (from env or default)
  browser_ctx — A fresh Playwright browser context per test (auto-close)
  page        — A Playwright Page object derived from browser_ctx

Environment variables:
  PLAYWRIGHT_BASE_URL — defaults to https://camiloavila.dev
                        Set to http://localhost:5173 for local testing

Report:
  HTML report generated by pytest-html:
    pytest --html=reports/e2e/playwright/report.html --self-contained-html

Run locally:
  pip install playwright pytest pytest-html
  playwright install chromium
  PLAYWRIGHT_BASE_URL=http://localhost:5173 pytest tests/e2e/playwright/ -v
"""

import os
import pytest
from playwright.sync_api import sync_playwright, Browser, BrowserContext, Page


BASE_URL = os.environ.get("PLAYWRIGHT_BASE_URL", "https://camiloavila.dev")


@pytest.fixture(scope="session")
def playwright_instance():
    """Start a single Playwright instance for the entire test session.

    Yields:
        Playwright: The Playwright sync API instance.
    """
    with sync_playwright() as pw:
        yield pw


@pytest.fixture(scope="session")
def browser(playwright_instance):
    """Launch a headless Chromium browser for the test session.

    The browser is shared across all tests in the session to reduce
    startup overhead. Each test gets its own isolated context (below).

    Yields:
        Browser: The launched Chromium browser instance.
    """
    browser: Browser = playwright_instance.chromium.launch(
        headless=True,
        args=["--no-sandbox", "--disable-setuid-sandbox"],
    )
    yield browser
    browser.close()


@pytest.fixture
def browser_ctx(browser) -> BrowserContext:
    """Create a fresh browser context (isolated session) per test.

    Each test gets its own cookies, localStorage, and session state.

    Yields:
        BrowserContext: An isolated Playwright browser context.
    """
    context: BrowserContext = browser.new_context(
        viewport={"width": 1280, "height": 720},
        base_url=BASE_URL,
    )
    yield context
    context.close()


@pytest.fixture
def page(browser_ctx) -> Page:
    """Open a new page in the browser context and navigate to the portfolio.

    Navigates to the base URL before yielding the Page object.

    Yields:
        Page: A Playwright Page ready at the portfolio homepage.
    """
    p: Page = browser_ctx.new_page()
    p.goto(BASE_URL, wait_until="networkidle")
    yield p
    p.close()
