/**
 * ContactForm.tsx — Contact Section with Automated Email Form
 *
 * Renders the contact section of the portfolio with:
 * - A brief invitation to connect
 * - A form with name, email, and message fields
 * - Client-side validation with inline error messages
 * - POST request to the API Gateway /contact endpoint
 * - Success and error state feedback
 *
 * On successful submission, the visitor receives an automated personalised
 * reply email generated by the ContactAgent (Bedrock + Strands).
 *
 * The API URL is read from the VITE_API_URL environment variable.
 * See frontend/.env.example for setup instructions.
 */

import React, { useState } from "react";

/** Form field values. */
interface FormValues {
  name: string;
  email: string;
  message: string;
}

/** Per-field validation errors. */
interface FormErrors {
  name?: string;
  email?: string;
  message?: string;
}

/** Possible submission states. */
type SubmitStatus = "idle" | "loading" | "success" | "error";

const EMAIL_REGEX = /^[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}$/;
const API_URL = import.meta.env.VITE_API_URL ?? "";

/**
 * Validate form values and return an errors object.
 * An empty object means all fields are valid.
 *
 * @param values - Current form values to validate.
 * @returns An object containing error messages for invalid fields.
 */
function validate(values: FormValues): FormErrors {
  const errors: FormErrors = {};

  if (!values.name.trim()) {
    errors.name = "Name is required.";
  }

  if (!values.email.trim()) {
    errors.email = "Email is required.";
  } else if (!EMAIL_REGEX.test(values.email)) {
    errors.email = "Please enter a valid email address.";
  }

  if (!values.message.trim()) {
    errors.message = "Message is required.";
  } else if (values.message.trim().length > 2000) {
    errors.message = "Message must be under 2000 characters.";
  }

  return errors;
}

/**
 * Contact form component.
 *
 * @returns The contact section with introduction text and submission form.
 */
const ContactForm: React.FC = () => {
  const [values, setValues] = useState<FormValues>({
    name: "",
    email: "",
    message: "",
  });
  const [errors, setErrors] = useState<FormErrors>({});
  const [status, setStatus] = useState<SubmitStatus>("idle");
  const [serverMessage, setServerMessage] = useState("");

  /**
   * Update a single form field value and clear its error.
   *
   * @param field - The field name to update.
   * @param value - The new value.
   */
  const handleChange = (
    field: keyof FormValues,
    value: string
  ) => {
    setValues((prev) => ({ ...prev, [field]: value }));
    if (errors[field]) {
      setErrors((prev) => ({ ...prev, [field]: undefined }));
    }
  };

  /**
   * Handle form submission.
   * Validates fields, then POSTs to /contact endpoint.
   *
   * @param e - Form submit event.
   */
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const validationErrors = validate(values);
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors);
      return;
    }

    setStatus("loading");
    setServerMessage("");

    try {
      const response = await fetch(`${API_URL}/contact`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(values),
      });

      const data = await response.json();

      if (response.ok) {
        setStatus("success");
        setServerMessage(data.message ?? "Message sent successfully!");
        setValues({ name: "", email: "", message: "" });
      } else {
        setStatus("error");
        setServerMessage(data.error ?? "Something went wrong. Please try again.");
      }
    } catch {
      setStatus("error");
      setServerMessage(
        "Could not reach the server. Please check your connection and try again."
      );
    }
  };

  return (
    <section id="contact" aria-labelledby="contact-heading">
      <h2 className="section-heading" id="contact-heading">
        <span className="section-number">04.</span> Get In Touch
      </h2>

      <div style={styles.intro}>
        <p style={styles.introText}>
          I'm currently available for Senior QA Automation Engineer roles with a
          focus on AI and cloud. Whether you have a question, a project in mind,
          or just want to say hi — my inbox is open.
        </p>
        <p style={styles.introContact}>
          You can also reach me directly at{" "}
          <a href="mailto:camiloavilainfo@gmail.com">
            camiloavilainfo@gmail.com
          </a>{" "}
          or{" "}
          <a
            href="https://www.linkedin.com/in/camiloavila"
            target="_blank"
            rel="noopener noreferrer"
          >
            LinkedIn
          </a>
          .
        </p>
      </div>

      {status === "success" ? (
        <div style={styles.successBox} role="alert">
          <p style={styles.successText}>✓ {serverMessage}</p>
          <p style={styles.successSub}>
            Check your inbox — a personalised reply is on its way.
          </p>
          <button
            style={styles.resetBtn}
            onClick={() => setStatus("idle")}
            className="btn"
          >
            Send another message
          </button>
        </div>
      ) : (
        <form
          style={styles.form}
          onSubmit={handleSubmit}
          noValidate
          aria-label="Contact form"
        >
          {/* Name */}
          <div style={styles.field}>
            <label htmlFor="contact-name">Name</label>
            <input
              id="contact-name"
              type="text"
              placeholder="Your full name"
              value={values.name}
              onChange={(e) => handleChange("name", e.target.value)}
              aria-describedby={errors.name ? "name-error" : undefined}
              aria-invalid={!!errors.name}
              maxLength={100}
            />
            {errors.name && (
              <span id="name-error" style={styles.error} role="alert">
                {errors.name}
              </span>
            )}
          </div>

          {/* Email */}
          <div style={styles.field}>
            <label htmlFor="contact-email">Email</label>
            <input
              id="contact-email"
              type="email"
              placeholder="your@email.com"
              value={values.email}
              onChange={(e) => handleChange("email", e.target.value)}
              aria-describedby={errors.email ? "email-error" : undefined}
              aria-invalid={!!errors.email}
            />
            {errors.email && (
              <span id="email-error" style={styles.error} role="alert">
                {errors.email}
              </span>
            )}
          </div>

          {/* Message */}
          <div style={styles.field}>
            <label htmlFor="contact-message">
              Message
              <span style={styles.charCount}>
                {values.message.length}/2000
              </span>
            </label>
            <textarea
              id="contact-message"
              rows={6}
              placeholder="Tell me about the role, project, or question you have..."
              value={values.message}
              onChange={(e) => handleChange("message", e.target.value)}
              aria-describedby={errors.message ? "message-error" : undefined}
              aria-invalid={!!errors.message}
              maxLength={2000}
              style={styles.textarea}
            />
            {errors.message && (
              <span id="message-error" style={styles.error} role="alert">
                {errors.message}
              </span>
            )}
          </div>

          {/* Server error */}
          {status === "error" && (
            <div style={styles.serverError} role="alert">
              {serverMessage}
            </div>
          )}

          <button
            type="submit"
            className="btn"
            disabled={status === "loading"}
            aria-label="Send message"
          >
            {status === "loading" ? "Sending..." : "Send Message"}
          </button>
        </form>
      )}
    </section>
  );
};

const styles: Record<string, React.CSSProperties> = {
  intro: {
    maxWidth: "560px",
    marginBottom: "40px",
  },
  introText: {
    color: "var(--text-secondary)",
    fontSize: "16px",
    lineHeight: 1.7,
    marginBottom: "12px",
  },
  introContact: {
    color: "var(--text-secondary)",
    fontSize: "15px",
  },
  form: {
    maxWidth: "560px",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  textarea: {
    resize: "vertical",
    minHeight: "120px",
  },
  error: {
    color: "#ff6b6b",
    fontSize: "13px",
    fontFamily: "var(--font-mono)",
  },
  charCount: {
    marginLeft: "auto",
    float: "right",
    color: "var(--text-secondary)",
    fontWeight: 400,
  },
  serverError: {
    color: "#ff6b6b",
    background: "rgba(255, 107, 107, 0.08)",
    border: "1px solid rgba(255, 107, 107, 0.3)",
    borderRadius: "4px",
    padding: "12px 16px",
    fontSize: "14px",
  },
  successBox: {
    maxWidth: "560px",
    background: "rgba(100, 255, 218, 0.05)",
    border: "1px solid var(--accent)",
    borderRadius: "8px",
    padding: "32px",
  },
  successText: {
    color: "var(--accent)",
    fontSize: "18px",
    fontWeight: 500,
    marginBottom: "8px",
  },
  successSub: {
    color: "var(--text-secondary)",
    fontSize: "15px",
    marginBottom: "24px",
  },
  resetBtn: {
    marginTop: "0",
  },
};

export default ContactForm;
