"""
generate_reply.py — Strands Tool: AI Personalized Email Paragraph
==================================================================
A Strands Agent tool used by the ContactAgent to generate a single
personalised paragraph for the automated reply email sent to visitors.

The paragraph is generated by Amazon Bedrock (qwen.qwen3-coder-next) and
is tailored to the visitor's specific message — making each email reply
feel unique and relevant rather than a generic auto-response.

The full email structure (opening + this paragraph + footer) is assembled
in ses_client.py before sending via SES.

How it integrates:
  contact_handler.py
    → ContactAgent (strands agent)
      → generate_reply tool (this file)
        → Bedrock Converse API
          → returns AI paragraph
      → ses_client.send_contact_reply (assembles full email)
      → dynamo_client.save_contact (stores record for audit)
"""

import os
import logging
import json

import boto3
from strands import tool

logger = logging.getLogger(__name__)

_bedrock_client = boto3.client("bedrock-runtime", region_name="us-east-1")

_REPLY_SYSTEM_PROMPT = """You are helping Camilo Avila respond to someone who has contacted him 
through his portfolio website. Write a single short paragraph (3-4 sentences) that:
1. Acknowledges the visitor's specific message or question in a personalised way
2. Briefly mentions how Camilo's background is relevant to their interest
3. Encourages them to continue the conversation

Keep the tone professional but warm. Do not introduce yourself — the email already has
an opening paragraph. Do not add a closing — the email already has a footer.
Write only the single paragraph, nothing else."""


@tool
def generate_reply(visitor_name: str, visitor_message: str) -> str:
    """Generate a personalised email paragraph for a contact form visitor.

    Uses Amazon Bedrock to produce a short, contextually relevant paragraph
    that acknowledges the visitor's specific message and connects it to
    Camilo's professional background.

    Args:
        visitor_name:    The visitor's name from the contact form.
        visitor_message: The visitor's message from the contact form.

    Returns:
        str: A 3-4 sentence personalised paragraph suitable for inclusion
             in the automated reply email body.

    Raises:
        RuntimeError: If BEDROCK_MODEL_ID is not set.
        RuntimeError: If the Bedrock API call fails.

    Example:
        >>> para = generate_reply(
        ...     visitor_name="Jane",
        ...     visitor_message="I'm looking for a QA lead for our fintech startup.",
        ... )
        >>> assert len(para) > 50
        >>> assert "Jane" in para or "fintech" in para or "QA" in para
    """
    model_id = os.environ.get("BEDROCK_MODEL_ID", "qwen.qwen3-coder-next")

    logger.info(
        "Tool generate_reply called. visitor_name=%s model=%s",
        visitor_name,
        model_id,
    )

    user_message = (
        f"The visitor's name is: {visitor_name}\n\n"
        f"Their message: {visitor_message}\n\n"
        "Write the personalised paragraph for Camilo's reply email."
    )

    try:
        response = _bedrock_client.converse(
            modelId=model_id,
            system=[{"text": _REPLY_SYSTEM_PROMPT}],
            messages=[
                {
                    "role": "user",
                    "content": [{"text": user_message}],
                }
            ],
            inferenceConfig={
                "maxTokens": 256,
                "temperature": 0.7,  # Higher creativity for email tone
                "topP": 0.9,
            },
        )

        paragraph = response["output"]["message"]["content"][0]["text"].strip()
        logger.info(
            "AI reply paragraph generated successfully (%d chars).", len(paragraph)
        )
        return paragraph

    except Exception as exc:
        logger.error("Bedrock generate_reply failed: %s", str(exc))
        # Fallback paragraph — ensures the email still sends even if AI fails
        return (
            f"Thank you for your message, {visitor_name}. I've read your note carefully "
            "and I'm looking forward to learning more about your needs. "
            "I'll be in touch soon to continue the conversation."
        )
